# Generated by Django 3.0.7 on 2020-06-11 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
