# Generated by Django 3.0.7 on 2020-06-19 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0003_auto_20200611_1430'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='Codinome')),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/', verbose_name='Avatar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mestre',
                'verbose_name_plural': 'Mestres',
            },
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='Nome')),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/', verbose_name='Avatar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Master', verbose_name='Mestre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, verbose_name='Nome')),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/', verbose_name='Avatar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Gamer', verbose_name='Mestre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Torcedor',
                'verbose_name_plural': 'Torcedores',
            },
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='word',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.Gamer', verbose_name='Mestre'),
        ),
        migrations.AddField(
            model_name='word',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='words.Master', verbose_name='Mestre'),
        ),
    ]
