# Generated by Django 3.0.7 on 2020-06-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplace', '0001_initial'),
        ('words', '0005_auto_20200620_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='master',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='master',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='master',
            name='user',
        ),
        migrations.AlterField(
            model_name='word',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplace.Gamer', verbose_name='Masters'),
        ),
        migrations.AlterField(
            model_name='word',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplace.Master', verbose_name='Masters'),
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
