# Generated by Django 3.0.7 on 2020-08-08 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0008_right'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='right',
            options={'verbose_name': 'Right', 'verbose_name_plural': 'Rights'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='right',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-08-09 19:57:00', verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplace.Gamer', verbose_name='Gamer'),
        ),
        migrations.AddField(
            model_name='right',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='right',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='word',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplace.Gamer', verbose_name='Gamer'),
        ),
    ]
