# Generated by Django 3.0.7 on 2020-10-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField(default=False, verbose_name='authorized')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplace.Gamer', verbose_name='gamer')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplace.Master', verbose_name='master')),
            ],
        ),
        migrations.AddField(
            model_name='gamer',
            name='othersMasters',
            field=models.ManyToManyField(related_name='otherMasters', through='gameplace.GamerMaster', to='gameplace.Master'),
        ),
    ]
