# Generated by Django 3.0.7 on 2020-10-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20201001_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/', verbose_name='Photo'),
        ),
    ]
